# playbook-create-users3.yml
---
-
  name: Create users
  hosts: localhost
  tasks:
    - user: name='{{ item }}' state=present
      with_items:
        - user1
        - user2
        - user3
        - user4
    - debug: var=item
      with_file:
        - /etc/hosts
        - /etc/resolv.conf
        - /etc/ntp.conf
