# playbook-create-users1.yml
---
-
  name: Create users
  hosts: vm2
  tasks:
    - user: name='{{ item }}' state=absent remove=yes
    # - user: name='{{ item }}' state=present
      loop:
        - user1
        - user2
        - user3
        - user4
