# playbook-conditionals-loops.yml
---
- name: Install Softwares
  hosts: all
  vars:
    packages:
      - name: nginx
        required: Yes
      - name: php
        required: Yes
      - name: mysql
        required: Yes
      - name: apache
        required: No
  tasks:
  - name: Install {{ item.name }} on Debian
    apt:
      name: "{{ item.name }}"
      state: present
    when: item.required == 'Yes' and ansible_os_family == 'Debian' and ansible_distribution_version >= '8' 
    loop: "{{ packages }}"
