# playbook-create-users2.yml
---
-
  name: Create users
  hosts: vm2
  tasks:
    # - user: name={{ item.name }} uid={{ item.uid }} groups={{ item.groups }} state=present
    - user: name={{ item.name }} uid={{ item.uid }} groups={{ item.groups }} state=absent remove=yes
      loop:
        - name: user1 
          uid: 1011 
          groups: wheel
        - name: user2 
          uid: 1012 
          groups: users
        - name: user3
          uid: 1013
          groups: users
        - name: user4
          uid: 1014
          groups: users
